#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#$(PROJECT_PATH)/components 	\

PROJECT_NAME := spi_master
#EXTRA_COMPONENT_DIRS ?=
#COMPONENT_DIRS := 	$(PROJECT_PATH)/components 	\
#					$(PROJECT_PATH)/BSP			\
#					$(EXTRA_COMPONENT_DIRS) 	\
#					$(IDF_PATH)/components 		\
#					$(PROJECT_PATH)/main		

include $(IDF_PATH)/make/project.mk

